apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easy-edit.fullname" . }}
  labels:
    {{- include "easy-edit.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc }}
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
